version: '3.3'

services:
  php:
    build: ./
    ports:
      - 5000:8000
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
